# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20181203_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
    ]
